config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  resources :events 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  default_scope -> { order(start_time: :asc) }

   validate  :start_end_check

   #時間の矛盾を防ぐ
   def start_end_check
     if self.start_time.present? && self.end_time.present?
       errors.add(:end, "が開始時刻を上回っています。正しく記入してください。") if self.start > self.end 
     end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all 
  end

  def new
    @event = Event.new
    render plain: render_to_string(partial: 'form_new', layout: false, locals: { event: @event })
  end

  def create
    @event = Event.new(params_event)
    if @event.save
      respond_to do |format|
        format.html { redirect_to root_path } 
        format.js  #create.js.erbを探してその中の処理を実行する
      end
    else
      respond_to do |format|
        format.js {render partial: "error" }
        #登録にエラーが起きたときはerror.js.erbを実行する
      end
    end
  end
    
  private
    
  def params_event
    params.require(:event).permit(:title, :start, :end)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form_new.html.erb
<div class="row">
      <%= form_with(model: @event, url: events_path, remote: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :plan, "内容"%>
        <%= f.text_field :plan, class:'form-control mb-3', required: true %> 
  

        <div class="form-inline text-left">
         <%= f.label :start,"開始時刻", {class:'control-label'}%>
         <%= f.datetime_select :start, {default: Date.today + 0.hours + 00.minutes, minute_step: 60}, class: 'form-control' %>
        </div>
         <br>
        <div class="form-inline text-left"> 
         <%= f.label :end,"終了時刻", {class:'control-label'}%>
         <%= f.datetime_select :end, {default: Date.today + 0.hours + 00.minutes, minute_step: 60}, class: 'form-control' %>
        </div>

        <%= f.submit "登録",   class: "btn btn-primary js-event-create-btn" %>
      <% end %>
</div>      

app/views/events/index.html.erb
<div id="calendar"></div>

<div id="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">

        </div>
      </div>
    </div>
  </div>
</div>  

<div id="response-modal" tabindex="0" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="error" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="response-modal-body">
        </div>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalendarApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>